server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: farmasterrae
          uri: lb://farmasterrae
          predicates:
            - Path=/api/farmasterrae/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/