eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

app:
  frontend:
    base-url: ${FRONTEND_URI:http://localhost:4200}