server:
  port: 8081

spring:
  h2:
    console:
      enabled: true # Permite acceder a una consola web para ver la base de datos
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:usercommanddb # URL de la base de datos en memoria
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Crea el esquema al iniciar y lo borra al apagar

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}